# fly.toml app configuration file generated for alhotriathlon on 2023-06-26T20:49:10+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "alhotriathlon"
primary_region = "arn"

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
